language: php

php:
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

matrix:
  include:
    - php: 7.0
      env: setup=lowest
    - php: 7.0
      env: setup=stable

sudo: false

before_install:
  - pip install --user codecov
  - if [[ $TRAVIS_PHP_VERSION != 7.1 ]] ; then phpenv config-rm xdebug.ini; fi
  - travis_retry composer self-update

install:
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --no-interaction --prefer-dist --no-suggest; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable --no-suggest; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable --no-suggest; fi

script: vendor/bin/phpunit --coverage-clover 'builds/clover.xml'

after_script:
  - php vendor/bin/codacycoverage clover builds/clover.xml

matrix:
  fast_finish: true

after_success:
  - codecov
